add setup-troubleshoot
hyperledger/cello pull request #541
Opened 2023-08-18 17:32 UTC by haowenmvp

add setup-troubleshoot
Operation not permitted when using Docker Desktop

2023-08-18 18:07 UTC, yeasy approved these changes

2023-08-18 18:09 UTC, yeasy requested changes
Please read the guideline here and add sign-off into the commit msg

https://github.com/hyperledger/cello/wiki/Contribution-Process

2023-08-18 20:37 UTC, haowenmvp commented
the sign-off has been added

2023-08-20 17:57 UTC, zhuyuanmao approved these changes

2023-08-22 00:28 UTC, yeasy approved these changes

2023-08-22 00:30 UTC, merged